document.write("<header>");
document.write("<nav>");
document.write('<a href="/"><img src="/assets/logo.png" alt="logo" width="100%" /></a>');
document.write("<ul>");
document.write('<li><a href="/">Home</a></li>');
document.write('<li><a href="/structures/royalFamily.html">Royal Family</a></li>');
document.write('<li><a href="/structures/royalAssets.html">Royal Assets</a></li>');
document.write('<li><a href="/structures/contact.html">Contact Us</a></li>');
document.write('</ul>');
document.write('</nav>');
document.write('</header>');